/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_fdcanvas_free: (a: number, b: number) => void;
export const fdcanvas_add_animation_to_node: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const fdcanvas_create_node_at: (a: number, b: number, c: number, d: number, e: number) => number;
export const fdcanvas_delete_selected: (a: number) => number;
export const fdcanvas_duplicate_selected: (a: number) => number;
export const fdcanvas_get_annotations_json: (a: number, b: number, c: number) => [number, number];
export const fdcanvas_get_node_animations_json: (a: number, b: number, c: number) => [number, number];
export const fdcanvas_get_node_bounds: (a: number, b: number, c: number) => [number, number];
export const fdcanvas_get_selected_id: (a: number) => [number, number];
export const fdcanvas_get_selected_ids: (a: number) => [number, number];
export const fdcanvas_get_selected_node_props: (a: number) => [number, number];
export const fdcanvas_get_text: (a: number) => [number, number];
export const fdcanvas_get_tool_name: (a: number) => [number, number];
export const fdcanvas_group_selected: (a: number) => number;
export const fdcanvas_handle_key: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const fdcanvas_handle_pointer_down: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const fdcanvas_handle_pointer_move: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const fdcanvas_handle_pointer_up: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const fdcanvas_handle_stylus_squeeze: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const fdcanvas_has_pending_text_change: (a: number) => number;
export const fdcanvas_hit_test_at: (a: number, b: number, c: number) => [number, number];
export const fdcanvas_hit_test_badge: (a: number, b: number, c: number) => [number, number];
export const fdcanvas_new: (a: number, b: number) => number;
export const fdcanvas_redo: (a: number) => number;
export const fdcanvas_remove_node_animations: (a: number, b: number, c: number) => number;
export const fdcanvas_render: (a: number, b: any, c: number) => void;
export const fdcanvas_resize: (a: number, b: number, c: number) => void;
export const fdcanvas_select_by_id: (a: number, b: number, c: number) => number;
export const fdcanvas_set_annotations_json: (a: number, b: number, c: number, d: number, e: number) => number;
export const fdcanvas_set_node_prop: (a: number, b: number, c: number, d: number, e: number) => number;
export const fdcanvas_set_text: (a: number, b: number, c: number) => number;
export const fdcanvas_set_theme: (a: number, b: number) => void;
export const fdcanvas_set_tool: (a: number, b: number, c: number) => void;
export const fdcanvas_undo: (a: number) => number;
export const fdcanvas_ungroup_selected: (a: number) => number;
export const parse_to_json: (a: number, b: number) => [number, number];
export const validate: (a: number, b: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
